### ISSUE TITLE
RuntimeError: output with shape [1, 112, 112] doesn't match the broadcast shape [3, 112, 112]

### ISSUE THREAD

**Issue by huytuong010101** [wtnthu/DotFAN#2]
I see this bug when run `norm.sh` or `augmentation.sh`
Can you help me :(((
```
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\FTechAI\DotFAN\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\FTechAI\DotFAN\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\FTechAI\DotFAN\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\FTechAI\DotFAN\data_loader.py", line 127, in __getitem__
    return self.transform(image), self.filenames_path[index],torch.tensor(self.pie_pose)
  File "D:\FTechAI\DotFAN\venv\lib\site-packages\torchvision\transforms\transforms.py", line 60, in __call__
    img = t(img)
  File "D:\FTechAI\DotFAN\venv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\FTechAI\DotFAN\venv\lib\site-packages\torchvision\transforms\transforms.py", line 221, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "D:\FTechAI\DotFAN\venv\lib\site-packages\torchvision\transforms\functional.py", line 335, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 112, 112] doesn't match the broadcast shape [3, 112, 112]
```

**Comment by wtnthu** [comment]
You can change the pytorch version to 0.4.1 which can solve this problem.

**Comment by huytuong010101** [comment]
> You can change the pytorch version to 0.4.1 which can solve this problem.

Yes i pull requirement.txt, reinstall then it work
But can i augmentation with RGB color output image? does this repo includes this feature?

**Comment by wtnthu** [comment]
Because this is a product of a collaborative project, we released a trained model for garyscale images with our source code. However, you can train a rgb model on rgb faces by using our source code. You can change the setting: --gray="False".

**Comment by huytuong010101** [comment]
Okey thank u so much
